CREATE DATABASE cadastro;
USE cadastro;

CREATE TABLE usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    GMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN NOT NULL
);